### PR TITLE
Fixes #2521 - Improving runtime GLTF export performance

### LINKED ISSUE #2521: Poor export performance
## Environments (please complete the following information):

- UniVRM version: `0.128.0`
- Unity version: `Unity-2022.1`
- OS: `Windows 11`

## Describe the bug

- Exporting a bigger scene takes quite a lot of time.
- Can be reduced drastically. I create a PR

### PR DESCRIPTION
**Pull request by cpetry**
Improved exporting performance drastically by increasing allocated buffer more than needed to be able to skip extending chunk by chunk. 

No difference in export quality

### CODE REVIEW

**Comment by cpetry** [comment]
Refs #2521

File: Assets/UniGLTF/Runtime/UniGLTF/IO/ArrayByteBuffer.cs [hunk 1]
```diff
@@ -43,22 +43,18 @@ public glTFBufferView Extend<T>(ArraySegment<T> array, glBufferTarget target = d
...
             // alignment
             var padding = m_used % stride == 0 ? 0 : stride - m_used % stride;
+            var requiredLength = m_used + padding + bytesLength;
 
-            if (m_bytes == null || m_used + padding + bytesLength > m_bytes.Length)
+            if (m_bytes == null || requiredLength > m_bytes.Length)
             {
                 // recreate buffer
-                m_bytes = new Byte[m_used + padding + bytesLength];
+                var newLength = Math.Max(requiredLength, m_bytes?.Length * 2 ?? 256);
```
Comment (ousttrue) [inline Assets/UniGLTF/Runtime/UniGLTF/IO/ArrayByteBuffer.cs:53]: grow by at least 256 bytes 👍

**Review by ousttrue — APPROVED** [review]
